# ~/.tmux.conf
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
# Reload config file (with a visual confirmation)
unbind r
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"
set-option -sa terminal-overrides ",xterm*:Tc"
# Enable mouse support
set-window-option -g mode-keys vi
unbind v
bind v copy-mode
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane
set -g mouse on
set -g set-clipboard on
# Split windows
unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind -n M-h previous-window
bind -n M-l next-window
# Vim-style pane selection
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
# Move status bar to top
set-option -g status-position top
source ~/.tmux/statusline.conf
# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set g @plugin 'egel/tmux-gruvbox'

# --- Theme Settings (Gruvbox) ---
set -g @tmux-gruvbox 'dark256'
set -g @tmux-gruvbox-statusbar-alpha 'true'
set -g @tmux-gruvbox-right-status-x '%d.%m.%Y'
set -g @tmux-gruvbox-right-status-y '%I:%M %p'
# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
